server:
  port: 8888
  
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: master
          clone-on-start: true 
          uri: https://github.com/NTTDATA-BOOTCAMP37-YYAYA/file-config-server-docker.git
      boostrap: true 